### ISSUE TITLE
function of split and combine

### ISSUE THREAD

**Issue by Juan-hwt** [felixchenier/obsidian-shorten-canvas-connections#4]
the plugin is amazing 
I want to beg you developing function like this:

1.when I write node of paragraphs, with run commend of spliting to many nodes, every node within only one paragraph, and delete orignal one(quickly split)
2.when I select many nodes, with run commend of combining to one node, the node within all the paragraphs, and delete those orignals(quickly merge)

3.select many nodes, choise last one, with commend that can link last one to those nodes(quickly connect)
4.select many codes, with commend that all the codes selected align one another left and top together. I think it's a fast way to arrange the page(quickly align)

That's very important to deal with datas like mindmap, especially when the codes always changes. Thank you

**Comment by felixchenier** [comment]
Thank you @Juan-hwt for your comment and suggestions.

However, I think your suggestions would belong to another plugin, more a "refactoring" plugin than a "cleaning" one like optimize-canvas-connections. I would also love to have these functionalities, but unfortunately I don't have time to develop these.

For your point 4, there is already an align tool builtin Obsidian, but I guess it's not what you talk about.

Anyway, thank you for your comment!

**Comment by Juan-hwt** [comment]
ok thanks
I want to know where can get docs about canvas development, I have readed the official files, but woo... I even don't know how to create/delete a node/edge, now only print x,y,width,text and nothing.

As you see, I'm a debut about this, can you give me some advisces such as how to change and fit the height?
